# Generated by Django 5.2.7 on 2025-12-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, help_text='Razorpay Payment ID', max_length=100, null=True, unique=True)),
                ('razorpay_order_id', models.CharField(blank=True, help_text='Razorpay Order ID', max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, help_text='Razorpay Signature for verification', max_length=200, null=True)),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_phone', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in INR', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('body', models.TextField(help_text='Main content of the story (supports HTML)')),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image for the story', null=True, upload_to='stories/images/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo URL or direct video link. Will autoplay on story page.', null=True)),
                ('video_file', models.FileField(blank=True, help_text='Upload video directly (MP4 recommended). Will autoplay on story page.', null=True, upload_to='stories/videos/')),
                ('category', models.CharField(choices=[('education', 'Education'), ('health', 'Health'), ('food', 'Food')], default='education', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Story Post',
                'verbose_name_plural': 'Story Posts',
                'ordering': ['-created_date'],
            },
        ),
    ]
