# Generated by Django 6.0 on 2025-12-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerFormLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Volunteer Application Form', help_text='Title displayed in admin (for reference)', max_length=100)),
                ('form_url', models.URLField(help_text='Google Form or other form URL for volunteer applications')),
                ('is_active', models.BooleanField(default=True, help_text='When active, the Apply button links to this form. When inactive, a disclaimer popup is shown.')),
                ('disclaimer_message', models.TextField(default='Volunteer recruitment is currently closed. Please check back later or follow us on social media for updates.', help_text='Message shown when no active recruitment is available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Volunteer Form Link',
                'verbose_name_plural': 'Volunteer Form Links',
                'ordering': ['-updated_at'],
            },
        ),
    ]
