# Generated by Django 6.0 on 2025-12-25 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_volunteerformlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image to display in the story', upload_to='stories/images/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which images appear (lower = earlier)')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.storypost')),
            ],
            options={
                'verbose_name': 'Story Image',
                'verbose_name_plural': 'Story Images',
                'ordering': ['order'],
            },
        ),
    ]
