# Generated by Django 6.0 on 2025-12-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_storyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique identifier (e.g., home_hero_title)', max_length=100, unique=True)),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('what_we_do', 'What We Do'), ('ways_to_help', 'Ways to Help'), ('donate', 'Donate Page'), ('stories', 'Stories Page')], help_text='Which page this content belongs to', max_length=50)),
                ('section', models.CharField(help_text='Section name (e.g., Hero, Mission, CTA)', max_length=100)),
                ('label', models.CharField(help_text='Human-readable description of this content', max_length=200)),
                ('content_type', models.CharField(choices=[('text', 'Plain Text'), ('html', 'Rich Text (HTML)'), ('image', 'Image'), ('url', 'External URL')], default='text', max_length=20)),
                ('text_content', models.TextField(blank=True, help_text='Text or HTML content')),
                ('image_content', models.ImageField(blank=True, help_text='Image file (for image content type)', null=True, upload_to='site_content/')),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
                'ordering': ['page', 'section', 'key'],
            },
        ),
    ]
