# Generated by Django 5.2.7 on 2025-12-25 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('short_description', models.CharField(help_text='Brief description shown on project card (max 300 chars)', max_length=300)),
                ('full_description', models.TextField(help_text='Detailed description of the project (supports HTML)')),
                ('cover_image', models.ImageField(help_text='Main cover image for the project', upload_to='projects/covers/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo URL for project video', null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('upcoming', 'Upcoming')], default='ongoing', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Show this project on the website')),
                ('location', models.CharField(blank=True, help_text="Project location (e.g., 'Mehrauli, Delhi')", max_length=200)),
                ('beneficiaries_count', models.PositiveIntegerField(default=0, help_text='Number of children/beneficiaries impacted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='storypost',
            name='category',
            field=models.CharField(choices=[('education', 'Education')], default='education', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Gallery image for the project', upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which images appear (lower = first)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Update content (supports HTML)')),
                ('date', models.DateField(help_text='Date of the update')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='core.project')),
            ],
            options={
                'verbose_name': 'Project Update',
                'verbose_name_plural': 'Project Updates',
                'ordering': ['-date'],
            },
        ),
    ]
