# Generated by Django 6.0 on 2025-12-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_alter_storypost_category_projectimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique identifier for this media (auto-filled from location)', max_length=100, unique=True)),
                ('location', models.CharField(choices=[('home_hero_bg', 'Home - Hero Background'), ('home_impact_1', 'Home - Impact Photo 1'), ('home_impact_2', 'Home - Impact Photo 2'), ('home_impact_3', 'Home - Impact Photo 3'), ('home_impact_4', 'Home - Impact Photo 4'), ('home_impact_5', 'Home - Impact Photo 5'), ('home_impact_6', 'Home - Impact Photo 6'), ('home_impact_7', 'Home - Impact Photo 7'), ('home_impact_8', 'Home - Impact Photo 8'), ('home_placeholder_1', 'Home - Placeholder Story 1'), ('home_placeholder_2', 'Home - Placeholder Story 2'), ('home_placeholder_3', 'Home - Placeholder Story 3'), ('about_hero_bg', 'About - Hero Background'), ('whatwedo_hero_bg', 'What We Do - Hero Background'), ('whatwedo_mission_1', 'What We Do - Mission Image 1'), ('whatwedo_mission_2', 'What We Do - Mission Image 2'), ('waystohelp_hero_bg', 'Ways to Help - Hero Background'), ('donate_hero_bg', 'Donate - Hero Background'), ('stories_hero_video', 'Stories - Hero Video'), ('navbar_logo', 'Navbar Logo'), ('footer_logo', 'Footer Logo')], help_text='Where this media appears on the website', max_length=50, unique=True)),
                ('label', models.CharField(help_text='Human-readable description of this media', max_length=200)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Upload image (JPG, PNG, WebP recommended)', null=True, upload_to='static_media/')),
                ('video', models.FileField(blank=True, help_text='Upload video file (MP4 recommended)', null=True, upload_to='static_media/videos/')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='When inactive, fallback/default media will be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Static Media',
                'verbose_name_plural': 'Static Media',
                'ordering': ['location'],
            },
        ),
    ]
