# Generated by Django 6.0 on 2025-12-27 12:52

from django.db import migrations, models


def clear_donations(apps, schema_editor):
    Donation = apps.get_model('core', 'Donation')
    Donation.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_staticmedia'), # Assuming 0006 is the previous one, check file content
    ]

    operations = [
        migrations.RunPython(clear_donations),
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-date'], 'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donor_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_email',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_phone',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='razorpay_signature',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='donation',
            name='order_id',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.CharField(help_text='Amount in INR', max_length=100),
        ),
    ]
